version: 1.0.0
title: Makefile Initializer
description: >
  プロジェクトに最適なMakefileを自動生成し、GooseエージェントによるTDD・CI/CD連携を可能にします。
  使用言語・テストツールを検出し、test/lint/formatなどの共通ターゲットを用意します。

instructions: |
  このプロジェクトの構成ファイル（pyproject.toml, package.json, go.mod など）を調査し、
  使用されている言語・テストフレームワークに応じたMakefileを作成してください。

  最低限含めるべきターゲット：
  - make test
  - make lint
  - make format-check
  - make format
  - make flaky-check（必要に応じて）
  - make check（test + lint + format-check）

prompt: |
  このプロジェクトに最適なMakefileを生成してください。

extensions:
  - type: stdio
    name: serena
    cmd: uvx
    args:
      - --from
      - git+https://github.com/oraios/serena
      - serena
      - start-mcp-server
      - --context
      - agent
      - --project
      - $(pwd)
  - type: builtin
    name: computercontroller

activities:
  - "依存ファイルをもとにツールチェーンを判定"
  - "Makefileの構文と内容を提案"
  - "ターゲットごとの役割と使用例を出力"

settings:
  goose_provider: groq
  goose_model: openai/gpt-oss-120b
  temperature: 0.2

retry:
  max_retries: 1
  checks:
    - type: shell
      command: test -f Makefile
  on_failure: echo "❌ Makefile の生成に失敗しました"
